config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/index"
  get "/samples", to: 'samples#index'
  get '/contacts', to: 'contacts#new'
  get '/contacts/view_all', to: 'contacts#index'

  root to: 'home#index'

  resources :contacts, only: [:new, :create, :destroy]
  get '/events/archive' => 'events#archive'
  resources :events
  resources :songs
  resources :bios, path: '/about'
  resources :news_items, path: '/news'
  resources :reviews
  resources :slides
  resources :media_events, path: "/gallery"
  resources :media_images

  namespace :apis do
    post 'email/subscribe'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.erb
<div id="slideshow" data-url="<%= slides_path %>.json">
</div>

<div class="centered_content">
	<div class="two_thirds">
		<p>
		  Blackbird is a talented band made up of four musicians that are local to Portland, Oregon area in the beautiful Northwest.
		</p>

		<p>
		If you are looking to hire a band for your next event to give it that extra special touch that will have your guests dancing all night, and talking about your party for weeks, Blackbird is your band!
		</p><br>

		<%= link_to 'Contact Blackbird now', contacts_path, class: 'pseudo_button center' %>

		<p>
		Over years of playing weddings, festivals, and corporate parties Blackbird has developed a list of songs from the 50's all the way to current hits that everybody knows and loves. Whether you're looking to dance the night away to an all-Beatles set list, or a mix of classic rock, oldies, funk, and top 40, Blackbird can accomodate your needs. The band is always willing to learn special requests for your event.
		</p>

		<p>
		Blackbird is defined by a strong rhythm section driving the band and impressive vocals with bursts of 3 part harmony leading you through your favorite songs. Additionally, the band has a sound engineer skillfully guiding the sound through a high end sound system and a lighting setup to aid in creating an exciting atmosphere. With this setup, your guests are sure to enjoy themselves and dance all night while singing along.
		</p>

		<p>
		Blackbird has played a variety of events, and is prepared to accomodate a variety of special circumstances. They have played:
		</p>

		<ul class="bulleted">
		  <li>Weddings</li>
		  <li>Corporate Parties</li>
		  <li>Birthday Parties</li>
		  <li>Anniversary Parties</li>
		  <li>Festivals</li>
		  <li>Fundraisers</li>
		  <li>Backyard Parties</li>
		  <li>Restaurants/Bars</li>
		</ul>

		<p>If Blackbird sounds like a good fit for your event, we encourage you to look around this website. Please be sure to listen to audio samples by visiting the <%= link_to "song list", songs_path %> page, and check out some of Blackbird's <%= link_to "reviews", reviews_path %>.</p>

		<br>
		<%= link_to 'Contact Blackbird now', contacts_path, class: 'pseudo_button center' %>
	</div>

	<%= render partial: "layouts/right_third" %>

</div>
<div class="clear"></div>