config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/index"
  get "/samples", to: 'samples#index'
  get '/contacts', to: 'contacts#new'
  get '/contacts/view_all', to: 'contacts#index'

  root to: 'home#index'

  resources :contacts, only: [:new, :create, :destroy]
  get '/events/archive' => 'events#archive'
  resources :events
  resources :songs
  resources :bios, path: '/about'
  resources :news_items, path: '/news'
  resources :reviews
  resources :slides
  resources :media_events, path: "/gallery"
  resources :media_images

  namespace :apis do
    post 'email/subscribe'
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :summary, presence: true
  validates :accessible, presence: true
  validates :location, presence: true
  validates :date, presence: true
  validates :pay, presence: true

  scope :upcoming, -> { where("date >= ?", Date.today.to_datetime)}

  enum accessible: ['Public', 'Private', 'Unavailable', 'Available']
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :check_admin, only: [:new, :edit, :create, :update, :destroy]

  def index
    @events = Event.upcoming.order(:date)
    @display_events = []

    @display_events = Event.order(:date).map do |event|
      { summary: event.summary, accessible: event.accessible, location: event.location, date: event.date.strftime('%m-%d-%Y')}
    end
    
    respond_to do |format|
      format.html
      format.json { render json: @display_events }
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new()
  end

  def create
    @event = Event.create(event_params)
    if @event.save
      flash[:success] = "Event created!"
      redirect_to events_path
    else
      flash[:alert] = "There was an error; event was not created."
      redirect_to new_event_path
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update 
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:success] = "Changes saved!"
      redirect_to events_path
    else
      flash[:alert] = "Changes weren't saved."
      redirect_to edit_event_path(@event)
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event deleted."
    redirect_to events_path
  end

  def archive
    @events = Event.all.order(date: :desc)
  end

  private

  def event_params
    params.require(:event).permit(:summary, :location, :accessible, :date, :pay, :notes)
  end

  def check_admin
    unless user_signed_in?
      redirect_to root_path
    end  
  end

end

app/views/events/archive.html.erb
<div class="two_thirds">
  <div class="pushed_content">
    <h1>events archive</h1>

    <ul class="blocked">
    <% @events.each do |event| %>
      <li>
        <% if user_signed_in? %>
            <div class="pos_fr">
              <%= link_to edit_event_path(event) do %>
                <%= icon('edit', '', class: "pos_fr strong") %>
              <% end %>
            </div>
          <% end %>
        <span><%= event.date.strftime('%m.%d.%Y') %></span><br>
        <%= event.summary.html_safe %> <br>
        <%= event.location.html_safe %> 
        <% if user_signed_in? %>
          <div style="border: 1px solid #ddd; border-radius: 4px; padding: 1rem;">
            <h5>Internal info</h5>
            <em>Pay: <%= number_to_currency(event.pay / 100.0) %></em>
            <p>Notes: <%= event.notes %></p>
          </div>
        <% end %>
      </li>
    <% end %>
    </ul>
  </div>
</div>

<%= render partial: "layouts/right_third" %>

app/views/events/edit.html.erb
<h1>Edit</h1>

<%= simple_form_for @event do |form| %>
  <%= form.input :date, start_year: Time.now.year - 15,
  end_year: Time.now.year + 2 %>
  <%= form.input :accessible, collection: Event.accessibles.map { |item| [item[0], item[0]] }, include_blank: false %>
  <%= form.input :location %>
  <%= form.input :pay, as: :integer, hint: "In pennies, to avoid decimals." %>
  <%= form.input :summary, as: :text %>

  <%= form.button :submit %>
<% end %>

app/views/events/index.html.erb
<div class="two_thirds">
  <div class="pushed_content">
    <h1>events calendar</h1>

    <div id="calendar" data-url="<%= events_path %>"></div>


    <%= link_to "Add event", new_event_path if user_signed_in? %>
    <br><br>
    <h1>
      event list
      <%= link_to "View archive", events_archive_path %>
    </h1>
    <ul class="blocked">
    <% @events.each do |event| %>
      <li>
        <% if user_signed_in? %>
            <div class="pos_fr">
              <%= link_to edit_event_path(event) do %>
                <%= icon('edit', '', class: "pos_fr strong") %>
              <% end %>
            </div>
          <% end %>
        <span><%= event.date.strftime('%m.%d.%Y') %></span><br>
        <%= event.summary %> <br>
        <%= event.location %> 
        <% if user_signed_in? %>
          <div style="border: 1px solid #ddd; border-radius: 4px; padding: 1rem;">
            <h5>Internal info</h5>
            <em>Pay: <%= number_to_currency(event.pay / 100.0) %></em>
            <p>Notes: <%= event.notes %></p>
          </div>
        <% end %>
      </li>
    <% end %>
    </ul>
  </div>
</div>

<%= render partial: "layouts/right_third" %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= simple_form_for @event do |form| %>
  <%= form.input :date, start_year: Time.now.year - 15,
  end_year: Time.now.year + 2 %>
  <%= form.input :accessible, collection: Event.accessibles.map { |item| [item[0], item[0]] }, include_blank: false %>
  <%= form.input :location %>
  <%= form.input :pay, as: :integer, hint: "In pennies, to avoid decimals." %>
  <%= form.input :summary, as: :text %>
  <%= form.input :notes, as: :text, hint: "This will only be visible to admin." %>

  <%= form.button :submit %>
<% end %>

app/views/events/show.html.erb
<div class="two_thirds">
  <div class="pushed_content">
    <h1>event</h1>

    <div class="blocked">
    	<h3><%= @event.date.strftime('%m.%d.%Y') %></h3>
    	<p><%= @event.summary %></p>
    	<p><%= @event.location %></p>
    </div>
	
	<br>
    <%= link_to "View all", events_path %>
  </div>
</div>

<%= render partial: "layouts/right_third" %>