config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/index"
  get "/samples", to: 'samples#index'
  get '/contacts', to: 'contacts#new'
  get '/contacts/view_all', to: 'contacts#index'

  root to: 'home#index'

  resources :contacts, only: [:new, :create, :destroy]
  get '/events/archive' => 'events#archive'
  resources :events
  resources :songs
  resources :bios, path: '/about'
  resources :news_items, path: '/news'
  resources :reviews
  resources :slides
  resources :media_events, path: "/gallery"
  resources :media_images

  namespace :apis do
    post 'email/subscribe'
  end
end

app/models/song.rb
class Song < ApplicationRecord
  mount_uploader :sound_clip, SoundClipUploader
  
  validates_presence_of :title
  validates_presence_of :artist
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :check_admin, only: [:new, :edit, :create, :update, :destroy] 

  def index
    @songs = Song.all.order(:title)
  end

  def new
    @song = Song.new()
  end

  def create
    @song = Song.create(song_params)

    if @song.save
      flash[:success] = "Song added!"
      redirect_to songs_path
    else
      flash[:alert] = "Error in the save process."
      redirect_to new_song_path
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update 
    @song = Song.find(params[:id])
    @song.update(song_params)
    
    if @song.save
      flash[:success] = "Changes saved!"
      redirect_to songs_path
    else
      flash[:alert] = "Changes weren't saved."
      redirect_to edit_song_path(@song)
    end
  end

  def destroy
    @song = Song.find(params[:id])

    if @song.destroy
      flash[:success]  = "Song deleted."
      redirect_to songs_path
    else 
      flash[:alert] = "Error in deleting song."
      redirect_to edit_song_path(@song)
    end
  end

  private
  
  def song_params
    params.require(:song).permit(:title, :artist, :sound_clip)
  end

  def check_admin
    unless user_signed_in?
      redirect_to root_path
    end  
  end
end

app/views/songs/_form.html.erb
<%= simple_form_for song do |form| %>
  <%= form.input :title %>
  <%= form.input :artist %>
  <%= form.input :release_date, label: 'Release Year' %>
  <%= form.file_field :sound_clip %>
  <br>
  <%= form.button :submit %>
<% end %>

app/views/songs/_song.html.erb
<li>
  <% if song.sound_clip.present? %>
    <%= link_to song.title, song.sound_clip.url, target: '_blank' %>
     - <span>
         <%= song.artist %><%= " - #{song.release_date}" if song.release_date.present? %>
       </span> <%= link_to raw("<i class='fa fa-volume-up'></i>"), song.sound_clip.url, target: '_blank' %>
  <% else %>
    <%= song.title %> - <span><%= song.artist %></span><%= " - #{song.release_date}" if song.release_date.present? %>
  <% end %>
  <% if user_signed_in? %>
    <%= link_to edit_song_path(song) do %>
      <%= icon('edit', '', class: "strong") %>
    <% end %>
  <% end %>
</li>

app/views/songs/edit.html.erb
<h1>Edit song</h1>

<%= render partial: "form", locals: { song: @song } %>
<%= link_to "Delete", song_path(@song), method: :delete, :data => {:confirm => 'Are you sure?'} %>

app/views/songs/index.html.erb
<div class="two_thirds">  
  <div class="pushed_content translucent">
    <h1>
      song list
      <% if user_signed_in? %>
        <%= link_to "Add new song", new_song_path, class: "pseudo_button" %>
      <% end %>
    </h1>

    <p>
      Although the band mostly plays classic rock, they enjoy many types of music and they continue to add to their catalogue.
      <br>
    </p>
    <p>
      Below is a list of songs that Blackbird has performed at previous events.
    </p>

    <ul class="songs blocked" style='border-top: 1px solid #ddd; margin-top: 1em; padding-top: 1em;'>
      <%= render partial: 'songs/song', collection: @songs %>
    </ul>
  </div>
</div>
<%= render partial: "layouts/right_third" %>

app/views/songs/new.html.erb
<h1>Add a song</h1>

<%= render partial: "form", locals: { song: @song } %>