config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/index"
  get "/samples", to: 'samples#index'
  get '/contacts', to: 'contacts#new'
  get '/contacts/view_all', to: 'contacts#index'

  root to: 'home#index'

  resources :contacts, only: [:new, :create, :destroy]
  get '/events/archive' => 'events#archive'
  resources :events
  resources :songs
  resources :bios, path: '/about'
  resources :news_items, path: '/news'
  resources :reviews
  resources :slides
  resources :media_events, path: "/gallery"
  resources :media_images

  namespace :apis do
    post 'email/subscribe'
  end
end

app/views/layouts/_email_signup.html.erb
<h2>Event Notifications</h2>
<div id="email_signup_form">
<%= form_tag(apis_email_subscribe_path, method: "post", id: "subscribe", remote: "true") do -%>
   <%= email_field(:email, :address, {id: "email", placeholder: "Email address"}) %>
   <%= submit_tag("Sign me up!") %>
<% end %>
</div>
<div id="email_signup_spinner">
  <div class="center">Signing up...</div>
  <div class="loader"></div>
</div>
<div id="email_signup_message"></div>

app/views/layouts/_news.html.erb
<div>
  <h2>News</h2>
  <div>
  	<p>
    	<%= NewsItem.published.first.content.html_safe %>
    </p>
  </div>
</div>

app/views/layouts/_right_third.html.erb
<div class="one_third">
  <div>
    <h2>Events</h2>
    <% if @upcoming_events.present? %>
      <ul>
        <% @upcoming_events.each do |event| %>
          <li>
            <%= link_to event_path(event) do %>
              <span>
                <%= event.date.strftime('%m.%d.%Y') %>
              </span> - 
              <%= event.summary %><br>

            <% end %>
          </li>
        <% end %>
      </ul>
      <%= link_to "View All", events_path, class: "view_all_link" %>
    <% else %>
      <p><%= link_to 'Request Booking Info', contacts_path, class: 'pseudo_button' %></p>
      <%= link_to "View All", events_path, class: "view_all_link" %>
    <% end %>
  </div>

  <%= render partial: "layouts/news" if NewsItem.any? %>

  <div>
    <h2>Reviews</h2>
    <div id="review_widget" data-url="<%= reviews_url %>">
    </div>
    <%= link_to "View All", reviews_path, class: "view_all_link" %>
  </div>

  <div>
    <%= render partial: "layouts/email_signup" %>
  </div>
</div>

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
  <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blackbird</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,900,700,500,300italic,300|Rock+Salt' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag asset_path('blackbird.ico'), :rel => 'icon', :type => "image/x-icon" %>
</head>
<body>
    <section id="header">
      <div class="centered_content">
        <div class="home_links">
          <%= link_to root_path, id: "home_logo_link" do %>
            <%= image_tag 'blackbird_logo_grunge.png', class: "desktop_show" %>
            <%= image_tag 'mobile_logo1.png', class: "mobile_show" %>
          <% end %>
        </div>

        <div class="nav_links">
          <i id="nav_trigger" class="fa fa-bars mobile_show"></i>

          <ul id="nav_list">
            <li><%= link_to "about", bios_path %></li>
            <li><%= link_to "songlist", songs_path %></li>
            <li><%= link_to "calendar", events_path %></li>
            <li><%= link_to "gallery", media_events_path %></li>
            <li><%= link_to "reviews", reviews_path %></li>
            <li><%= link_to "contact us", contacts_path %></li>
          </ul>
        </div>
      </div>
    </section>
    <div class="clear"></div>
    <section id="content" class="<%= controller_name %>">
      <div class="centered_content">
        <div class="notice <%= notice ? '' : 'hidden' %>"><%= notice %></div>
        <div class="alert <%= alert ? '' : 'hidden' %>"><%= alert %></div>
        <%= yield %>
        <div class="clear"></div>
      </div>
    </section>
  <section id="footer">
    <div id="centered_content">
      <div id="social_media">
        <ul class="inline">
          <li>
            <%= link_to "http://www.facebook.com/BlackbirdOregon", target: "_blank" do %>
              <%= icon('facebook') %>
            <% end %>
          </li>
          <li>
            <%= link_to "http://www.youtube.com/BlackbirdOregon", target: "_blank" do %>
              <%= icon('youtube') %>
            <% end %>
          </li>
          <li>
            <%= link_to "http://www.twitter.com/BlackbirdOregon", target: "_blank" do %>
              <%= icon('twitter') %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clear"></div>
    </div>
  </section>

</body>
</html>